### ISSUE TITLE
Missing dependencies for 0.1.0?

### ISSUE THREAD

**Issue by jpvdm1** [oldrev/jsonrpc#1]
Hi,

Not sure if this only happens to me, but I have to add the following NuGet Packages for version 0.1.0 to run the sample in the readme:

System.Reflection.TypeExtensions
System.Runtime.Serialization.Primitives

Kind Regards,
JP

**Comment by oldrev** [comment]
Hi, 

I will check it later, thanks for trying it out.

Cheers!

**Comment by oldrev** [comment]
@jpvdm1 

I tried using it in both .NET Core App and a .NET Framework console app: in .NET Core app it works fine but in .NET Framework app it throws a FileNotFoundException that referenced those assemblies.

Surely it will be fixed ASAP, sorry for the inconvenience.

**Comment by oldrev** [comment]
Please upgrade to 0.1.1.33, it fixed the problem. So i am going to close this issue.
